### PR TITLE
Set ttl, msg priority, dmq eligible per message

### PR DESCRIPTION
**Pull request by GreenRover**
Add support for:
- per binder: msg priority
- per msg: msg priority
- per msg: ttl
- per msg: dmq eligible

### CODE REVIEW

**Comment by Nephery** [comment]
These message properties are already supported through PR #37. Referring to [the new documentation for Solace message headers](https://github.com/SolaceDev/solace-spring-cloud/tree/staging/solace-spring-cloud-starters/solace-spring-cloud-stream-starter#solace-headers), these properties will be supported via the following Spring Message headers:
* `solace_priority`
* `solace_timeToLive`
* `solace_dmqEligible`

For what its worth, we've also decided to remove the message property configuration from the binding config (`msgTtl` and `msgInternalDmqEligible`) in favor of just configuring the message properties on the message itself. It didn't really make much sense for message properties to be configurable in the binding config since these are only applied on the message itself.

**Comment by GreenRover** [comment]
Sounds god for me. When do you plan to merge #37?

Make it sense to base my further analyses on the related branch?

**Comment by Nephery** [comment]
I'll try to merge it tomorrow if you're OK with it conflicting with your other PR (#40).

> Make it sense to base my further analyses on the related branch?

Yeah it would be better for your analysis to be off of that since that is currently what is more-or-less stable.

**Comment by GreenRover** [comment]
In favor of #37 i reject this pullrequest

**Pull request closed without merging**
